'use client';
import {useState,useRef} from 'react';
import {useRouter} from 'next/navigation';
import Markdown from 'react-markdown';
import {collections,safeUrl,type Field} from '@/lib/cms';
type Row=Record<string,unknown>;
export default function Manager({collection,rows,role,options}:{collection:string;rows:Row[];role:string;options:Record<string,{value:string;label:string}[]>}){
 const spec=collections[collection],router=useRouter();
 const [selected,setSelected]=useState<Row|null>(null),[values,setValues]=useState<Row>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[preview,setPreview]=useState(false),[deleting,setDeleting]=useState(false);
 const editor=useRef<HTMLElement>(null),bodyRef=useRef<HTMLTextAreaElement>(null);
 function edit(row:Row){setSelected(row);setValues(Object.fromEntries(spec.fields.map(f=>[f.key,Array.isArray(row[f.key])?(row[f.key] as string[]).join(', '):row[f.key]??(f.key==='author_name'?'Zaane Studio':f.type==='select'?(f.options?.[0]||''):f.key==='rating'?5:f.key==='order'?0:'')])));setMessage('');setDeleting(false);setTimeout(()=>{editor.current?.scrollIntoView({behavior:'smooth',block:'start'});editor.current?.focus();},0);}
 async function save(action:'save'|'delete'){
  setBusy(true);setMessage('');try{const r=await fetch(`/api/admin/${collection}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:selected?.id,values})});const data=await r.json();if(!r.ok)throw new Error(data.error);setSelected(null);setMessage(action==='save'?'Saved successfully.':'Record deleted.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}
 }
 async function upload(f:Field,file?:File){if(!file)return;setBusy(true);setMessage('Uploading…');try{const data=new FormData();data.set('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:data});const result=await r.json();if(!r.ok)throw new Error(result.error);setValues(v=>({...v,[f.key]:result.url}));setMessage('Image uploaded. Save the record to attach it.');}catch(e){setMessage(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);}}
 function insert(before:string,after=''){const node=bodyRef.current;if(!node)return;const start=node.selectionStart,end=node.selectionEnd;const text=String(values.content||'');setValues(v=>({...v,content:text.slice(0,start)+before+text.slice(start,end)+after+text.slice(end)}));node.focus();}
 return <><div className="manager-toolbar"><label className="sr-only" htmlFor="record-search">Search loaded records</label><input id="record-search" placeholder="Search this page…" value={search} onChange={e=>setSearch(e.target.value)}/>{!spec.inbox&&<button className="studio-button black-button" onClick={()=>edit({})}>+ New {spec.label.toLowerCase()}</button>}{['leads','contact_submissions','subscribers'].includes(collection)&&<a className="text-link" href={`/api/admin/${collection}`}>Export CSV ↗</a>}</div>{collection==='users'&&<p className="notice">Create or invite an account in Supabase Authentication, then assign its staff role here. Unassigned accounts have no admin access.</p>}<p role="status" className="form-feedback">{message}</p><section className="admin-box">{rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).map(row=><div className="inbox-row" key={String(row.id)}><div><strong>{String(row.title||row.name||row.client_name||row.email||row.key||row.page_key||'Gallery image')}</strong><p>{String(row.excerpt||row.subject||row.service_interested||row.slug||row.role||row.section_key||'')}</p></div><span className="tag">{String(row.status||'')}</span><button className="text-link" onClick={()=>edit(row)}>Open ↗</button></div>)}{!rows.length&&<div className="empty-state"><h2>A fresh page.</h2><p>{spec.inbox?'New submissions will appear here.':'Create your first record when you’re ready.'}</p></div>}</section>
 {selected&&<section className="admin-box editor" ref={editor} tabIndex={-1}><div className="editor-heading"><h2>{selected.id?'Edit record':'New record'}</h2><button onClick={()=>{setSelected(null);setMessage('');}}>Close ×</button></div>{spec.inbox&&<dl className="record-details">{Object.entries(selected).filter(([k])=>!['id','status','role'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v??'-')}</dd></div>)}</dl>}
 <form onSubmit={e=>{e.preventDefault();void save('save');}} className="cms-form">{spec.fields.map(f=><div className="cms-field" key={f.key}><label htmlFor={`field-${f.key}`}>{f.label}{f.required?' *':''}</label>{f.type==='markdown'&&<div className="markdown-toolbar">{f.key==='content'&&<><button type="button" onClick={()=>insert('**','**')}>Bold</button><button type="button" onClick={()=>insert('## ')}>Heading</button><button type="button" onClick={()=>insert('- ')}>List</button><button type="button" onClick={()=>insert('[','](https://)')}>Link</button></>}<button type="button" aria-pressed={preview} onClick={()=>setPreview(!preview)}>{preview?'Write':'Preview'}</button></div>}
 {f.type==='select'?<select id={`field-${f.key}`} required={f.required} value={String(values[f.key]??'')} onChange={e=>setValues({...values,[f.key]:e.target.value})}>{!f.options&&<option value="">Select {f.label.toLowerCase()}</option>}{(f.options?.map(v=>({value:v,label:v||'No staff access'}))||options[f.key]||[]).filter(o=>!(role==='editor'&&o.value==='published')).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='boolean'?<input id={`field-${f.key}`} type="checkbox" checked={!!values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.checked})}/>:f.type==='textarea'||f.type==='markdown'?<>{preview&&f.type==='markdown'?<div className="prose markdown-preview"><Markdown>{String(values[f.key]||'Nothing to preview yet.')}</Markdown></div>:<textarea ref={f.key==='content'?bodyRef:undefined} id={`field-${f.key}`} rows={f.type==='markdown'?14:4} required={f.required} value={String(values[f.key]||'')} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>}</>:<input id={`field-${f.key}`} type={f.type==='number'?'number':'text'} required={f.required} value={String(values[f.key]??'')} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>}
 {f.type==='image'&&<><label className="upload-control">Upload image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy} onChange={e=>void upload(f,e.target.files?.[0])}/></label>{safeUrl(values[f.key])&&<img className="upload-preview" src={safeUrl(values[f.key])} alt="Selected image preview"/>}</>}
 </div>)}<div className="editor-actions">{!!spec.fields.length&&<button disabled={busy} className="studio-button orange-button">{busy?'Working…':'Save changes →'}</button>}{!!selected.id&&role!=='editor'&&collection!=='users'&&(deleting?<><span>Delete this record permanently?</span><button disabled={busy} type="button" className="danger-button" onClick={()=>void save('delete')}>Yes, delete</button><button type="button" onClick={()=>setDeleting(false)}>Cancel</button></>:<button type="button" className="danger-button" onClick={()=>setDeleting(true)}>Delete record</button>)}</div></form></section>}</>;
}
