import Link from 'next/link';
import Markdown from 'react-markdown';
import {safeUrl} from '@/lib/cms';
import type {ContentRow} from '@/lib/content';
export function PageHero({label,title,intro}:{label:string;title:string;intro:string}){return <section className="page-hero"><span className="eyebrow">{label}</span><h1>{title}</h1><p>{intro}</p><div className="hero-index" aria-hidden="true">Z<span>®</span></div></section>;}
export function Section({label,title,children,dark=false}:{label?:string;title:string;children:React.ReactNode;dark?:boolean}){return <section className={`content-section ${dark?'ink-section':''}`}><div className="content-heading">{label&&<span className="eyebrow">{label}</span>}<h2>{title}</h2></div>{children}</section>;}
export function CTA(){return <section className="final-cta"><span className="eyebrow">Your next chapter</span><h2>Good things start<br/>with a conversation.</h2><Link className="studio-button black-button" href="/services#inquiry">Let’s build something ↗</Link></section>;}
export function Copy({text}:{text:string}){return <div className="prose"><Markdown>{text}</Markdown></div>;}
export function Empty({title,body}:{title:string;body:string}){return <div className="empty-state"><span className="empty-mark" aria-hidden="true">↗</span><h3>{title}</h3><p>{body}</p></div>;}
export function ProjectCard({row}:{row:ContentRow}){return <Link className="project-card" href={`/projects/${row.slug}`}><div className="project-cover">{safeUrl(row.cover_image)?<img src={safeUrl(row.cover_image)} alt={String(row.title)} loading="lazy"/>:<span aria-hidden="true">{String(row.title).slice(0,1)}<i>↗</i></span>}</div><div className="project-card-caption"><h3>{String(row.title)}</h3><span>↗</span></div><p className="tagline">{String(row.category)} / {String(row.industry_tag)}</p><p>{String(row.short_description)}</p></Link>;}
export function PostCard({row,category}:{row:ContentRow;category?:string}){return <Link href={`/blog/${row.slug}`} className="post-card"><div className="post-cover">{safeUrl(row.cover_image)?<img src={safeUrl(row.cover_image)} alt="" loading="lazy"/>:<span>Notes<br/>from the studio. ↗</span>}</div><span className="tagline">{category||'Studio journal'} · {Math.max(1,Math.ceil(String(row.content||'').split(/\s+/).length/200))} min read</span><h3>{String(row.title)}</h3><p>{String(row.excerpt)}</p><small>{row.published_at?new Date(String(row.published_at)).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):''}</small></Link>;}
export function Testimonials({rows}:{rows:ContentRow[]}){return rows.length?<div className="testimonial-grid">{rows.map(r=><figure className="quote-card" key={r.id}><span aria-label={`${r.rating} out of 5 stars`} className="quote-stars">{'★'.repeat(Number(r.rating))}</span><blockquote>“{String(r.quote)}”</blockquote><figcaption>{safeUrl(r.photo_url)&&<img src={safeUrl(r.photo_url)} alt="" loading="lazy"/>}<div><strong>{String(r.client_name)}</strong><p>{String(r.client_role)}</p></div></figcaption></figure>)}</div>:<Empty title="The work comes first." body="Client stories will be shared here as they’re approved for publication."/>;}
